services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

# todo 后续修改数据库类型
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
      - --http-port=8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      # 外部访问的主机名（浏览器）
      KC_HOSTNAME_URL: http://localhost:8443
      KC_HOSTNAME_ADMIN_URL: http://localhost:8443

      # 非严格模式（允许内部服务用 keycloak:8080 调用）
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "false"

    ports:
      - "8443:8080"    # 外部访问 localhost:8443，对应容器内 8080
    volumes:
      - ./k8s/services/keycloak/configuration/ecomm-app-realm.json:/opt/keycloak/data/import/ecomm-app-realm.json:ro
      - ./k8s/services/keycloak/configuration/ecomm-app-users-0.json:/opt/keycloak/data/import/ecomm-app-users-0.json:ro
    networks:
      - backend



# todo 后续开启持久化
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - "5540:5540"
    networks:
      - backend

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CLUSTER_ID: test-cluster-id
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - backend
    restart: unless-stopped

  eureka:
    image: yixiwan/eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - backend
    depends_on:
      - mysql

  gateway:
    image: yixiwan/gateway-service:latest
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_DEFAULT_ZONE=http://eureka:8761/eureka
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_SSL_ENABLED=false
      - ALLOWED_ORIGINS=http://localhost:3000
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/ecomm-app
      - KEYCLOAK_AUTH_URL=http://localhost:8443/realms/ecomm-app/protocol/openid-connect/auth
      - KEYCLOAK_TOKEN_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/token
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/certs
      - KEYCLOAK_USERINFO_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/userinfo
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=0suFzByDwD8crmhf7oi8x4U1z52UaCCG
    networks:
      - backend
    depends_on:
      - eureka
      - keycloak
      - redis

  user:
    image: yixiwan/user-service:latest
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ecommerce
      - DB_USERNAME=user
      - DB_PASSWORD=user
      - EUREKA_DEFAULT_ZONE=http://eureka:8761/eureka
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=ecomm-app
      - KEYCLOAK_CLIENT_ID=ecomm-oauth2
      - KEYCLOAK_CLIENT_SECRET=0suFzByDwD8crmhf7oi8x4U1z52UaCCG
      - KEYCLOAK_USERNAME=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_ISSUER_URI=http://127.0.0.1:8443/realms/ecomm-app
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/certs
      - KEYCLOAK_TOKEN_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/token
    networks:
      - backend
    depends_on:
      - eureka
      - mysql
      - keycloak

  product:
    image: yixiwan/product-service:latest
    container_name: product-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ecommerce
      - DB_USERNAME=user
      - DB_PASSWORD=user
      - EUREKA_DEFAULT_ZONE=http://eureka:8761/eureka
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/ecomm-app
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/certs
      - KEYCLOAK_TOKEN_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/token
      - KEYCLOAK_CLIENT_SECRET=0suFzByDwD8crmhf7oi8x4U1z52UaCCG
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
      - CACHE_DATA_REDIS_HOST=redis
      - CACHE_DATA_REDIS_PORT=6379
      - CACHE_DATA_REDIS_SSL_ENABLED=false
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_SSL_ENABLED=false
    networks:
      - backend
    depends_on:
      - eureka
      - mysql
      - keycloak
      - kafka
      - redis

  order:
    image: yixiwan/order-service:latest
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ecommerce
      - DB_USERNAME=user
      - DB_PASSWORD=user
      - EUREKA_DEFAULT_ZONE=http://eureka:8761/eureka
      - KEYCLOAK_ISSUER_URI=http://127.0.0.1:8443/realms/ecomm-app
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/certs
      - KEYCLOAK_TOKEN_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/token
      - KEYCLOAK_CLIENT_SECRET=0suFzByDwD8crmhf7oi8x4U1z52UaCCG
    networks:
      - backend
    depends_on:
      - eureka
      - mysql
      - keycloak

  payment:
    image: yixiwan/payment-service:latest
    container_name: payment-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ecommerce
      - DB_USERNAME=user
      - DB_PASSWORD=user
      - EUREKA_DEFAULT_ZONE=http://eureka:8761/eureka
      - KEYCLOAK_ISSUER_URI=http://127.0.0.1:8443/realms/ecomm-app
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/certs
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
    networks:
      - backend
    depends_on:
      - eureka
      - mysql
      - keycloak
      - kafka

  inventory:
    image: yixiwan/inventory-service:latest
    container_name: inventory-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ecommerce
      - DB_USERNAME=user
      - DB_PASSWORD=user
      - EUREKA_DEFAULT_ZONE=http://eureka:8761/eureka
      - KEYCLOAK_ISSUER_URI=http://127.0.0.1:8443/realms/ecomm-app
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/certs
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
    networks:
      - backend
    depends_on:
      - eureka
      - mysql
      - keycloak
      - kafka

  cart:
    image: yixiwan/cart-service:latest
    container_name: cart-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_DEFAULT_ZONE=http://eureka:8761/eureka
      - KEYCLOAK_ISSUER_URI=http://localhost:8443/realms/ecomm-app
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/certs
      - KEYCLOAK_TOKEN_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/token
      - KEYCLOAK_CLIENT_SECRET=0suFzByDwD8crmhf7oi8x4U1z52UaCCG
    networks:
      - backend
    depends_on:
      - eureka
      - keycloak

  address:
    image: yixiwan/address-service:latest
    container_name: address-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ecommerce
      - DB_USERNAME=user
      - DB_PASSWORD=user
      - EUREKA_DEFAULT_ZONE=http://eureka:8761/eureka
      - KEYCLOAK_ISSUER_URI=http://127.0.0.1:8443/realms/ecomm-app
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/ecomm-app/protocol/openid-connect/certs
    networks:
      - backend
    depends_on:
      - eureka
      - mysql
      - keycloak

#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    ports:
#      - "8088:8080"
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=host.docker.internal:9092
#    depends_on:
#      - kafka
#    networks:
#      - backend

volumes:
  mysql_data:
  kafka_data:
  keycloak_data:


networks:
  backend:
    driver: bridge